language: cpp
sudo: required
matrix:
  include:
    # works on macOS with clang
    - os: osx
      osx_image: xcode10
      compiler: clang
      env: MATRIX_EVAL="CC=clang && CXX=clang++"

install:
  - |
    if [[ ${TRAVIS_OS_NAME} == "osx" ]]; then
      brew update
      brew install qt node
      npm install -g appdmg
    fi
script:
  - sh ./build.sh macosx release /usr/local/opt/qt